/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as TechnologiesRouteImport } from './routes/technologies'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AiSolutionsRouteImport } from './routes/ai-solutions'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsWebsiteGeneratorRouteImport } from './routes/tools.website-generator'
import { Route as ToolsThumbnailGeneratorRouteImport } from './routes/tools.thumbnail-generator'
import { Route as ToolsResumeBuilderRouteImport } from './routes/tools.resume-builder'
import { Route as ToolsProposalGeneratorRouteImport } from './routes/tools.proposal-generator'
import { Route as ToolsPortfolioBuilderRouteImport } from './routes/tools.portfolio-builder'
import { Route as ToolsDomainGeneratorRouteImport } from './routes/tools.domain-generator'
import { Route as ToolsChatbotSaasRouteImport } from './routes/tools.chatbot-saas'
import { Route as ToolsCaptionGeneratorRouteImport } from './routes/tools.caption-generator'
import { Route as ToolsAiHumanizerRouteImport } from './routes/tools.ai-humanizer'
import { Route as ToolsAiDetectorRouteImport } from './routes/tools.ai-detector'
import { Route as ToolsToolIdRouteImport } from './routes/tools.$toolId'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologiesRoute = TechnologiesRouteImport.update({
  id: '/technologies',
  path: '/technologies',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSolutionsRoute = AiSolutionsRouteImport.update({
  id: '/ai-solutions',
  path: '/ai-solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsWebsiteGeneratorRoute = ToolsWebsiteGeneratorRouteImport.update({
  id: '/website-generator',
  path: '/website-generator',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsThumbnailGeneratorRoute = ToolsThumbnailGeneratorRouteImport.update({
  id: '/thumbnail-generator',
  path: '/thumbnail-generator',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsResumeBuilderRoute = ToolsResumeBuilderRouteImport.update({
  id: '/resume-builder',
  path: '/resume-builder',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsProposalGeneratorRoute = ToolsProposalGeneratorRouteImport.update({
  id: '/proposal-generator',
  path: '/proposal-generator',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsPortfolioBuilderRoute = ToolsPortfolioBuilderRouteImport.update({
  id: '/portfolio-builder',
  path: '/portfolio-builder',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsDomainGeneratorRoute = ToolsDomainGeneratorRouteImport.update({
  id: '/domain-generator',
  path: '/domain-generator',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsChatbotSaasRoute = ToolsChatbotSaasRouteImport.update({
  id: '/chatbot-saas',
  path: '/chatbot-saas',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsCaptionGeneratorRoute = ToolsCaptionGeneratorRouteImport.update({
  id: '/caption-generator',
  path: '/caption-generator',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsAiHumanizerRoute = ToolsAiHumanizerRouteImport.update({
  id: '/ai-humanizer',
  path: '/ai-humanizer',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsAiDetectorRoute = ToolsAiDetectorRouteImport.update({
  id: '/ai-detector',
  path: '/ai-detector',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsToolIdRoute = ToolsToolIdRouteImport.update({
  id: '/$toolId',
  path: '/$toolId',
  getParentRoute: () => ToolsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-solutions': typeof AiSolutionsRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/services': typeof ServicesRoute
  '/technologies': typeof TechnologiesRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/tools/$toolId': typeof ToolsToolIdRoute
  '/tools/ai-detector': typeof ToolsAiDetectorRoute
  '/tools/ai-humanizer': typeof ToolsAiHumanizerRoute
  '/tools/caption-generator': typeof ToolsCaptionGeneratorRoute
  '/tools/chatbot-saas': typeof ToolsChatbotSaasRoute
  '/tools/domain-generator': typeof ToolsDomainGeneratorRoute
  '/tools/portfolio-builder': typeof ToolsPortfolioBuilderRoute
  '/tools/proposal-generator': typeof ToolsProposalGeneratorRoute
  '/tools/resume-builder': typeof ToolsResumeBuilderRoute
  '/tools/thumbnail-generator': typeof ToolsThumbnailGeneratorRoute
  '/tools/website-generator': typeof ToolsWebsiteGeneratorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-solutions': typeof AiSolutionsRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/services': typeof ServicesRoute
  '/technologies': typeof TechnologiesRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/tools/$toolId': typeof ToolsToolIdRoute
  '/tools/ai-detector': typeof ToolsAiDetectorRoute
  '/tools/ai-humanizer': typeof ToolsAiHumanizerRoute
  '/tools/caption-generator': typeof ToolsCaptionGeneratorRoute
  '/tools/chatbot-saas': typeof ToolsChatbotSaasRoute
  '/tools/domain-generator': typeof ToolsDomainGeneratorRoute
  '/tools/portfolio-builder': typeof ToolsPortfolioBuilderRoute
  '/tools/proposal-generator': typeof ToolsProposalGeneratorRoute
  '/tools/resume-builder': typeof ToolsResumeBuilderRoute
  '/tools/thumbnail-generator': typeof ToolsThumbnailGeneratorRoute
  '/tools/website-generator': typeof ToolsWebsiteGeneratorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-solutions': typeof AiSolutionsRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/services': typeof ServicesRoute
  '/technologies': typeof TechnologiesRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/tools/$toolId': typeof ToolsToolIdRoute
  '/tools/ai-detector': typeof ToolsAiDetectorRoute
  '/tools/ai-humanizer': typeof ToolsAiHumanizerRoute
  '/tools/caption-generator': typeof ToolsCaptionGeneratorRoute
  '/tools/chatbot-saas': typeof ToolsChatbotSaasRoute
  '/tools/domain-generator': typeof ToolsDomainGeneratorRoute
  '/tools/portfolio-builder': typeof ToolsPortfolioBuilderRoute
  '/tools/proposal-generator': typeof ToolsProposalGeneratorRoute
  '/tools/resume-builder': typeof ToolsResumeBuilderRoute
  '/tools/thumbnail-generator': typeof ToolsThumbnailGeneratorRoute
  '/tools/website-generator': typeof ToolsWebsiteGeneratorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-solutions'
    | '/blog'
    | '/contact'
    | '/portfolio'
    | '/pricing'
    | '/privacy-policy'
    | '/refund-policy'
    | '/services'
    | '/technologies'
    | '/terms-and-conditions'
    | '/tools'
    | '/tools/$toolId'
    | '/tools/ai-detector'
    | '/tools/ai-humanizer'
    | '/tools/caption-generator'
    | '/tools/chatbot-saas'
    | '/tools/domain-generator'
    | '/tools/portfolio-builder'
    | '/tools/proposal-generator'
    | '/tools/resume-builder'
    | '/tools/thumbnail-generator'
    | '/tools/website-generator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-solutions'
    | '/blog'
    | '/contact'
    | '/portfolio'
    | '/pricing'
    | '/privacy-policy'
    | '/refund-policy'
    | '/services'
    | '/technologies'
    | '/terms-and-conditions'
    | '/tools'
    | '/tools/$toolId'
    | '/tools/ai-detector'
    | '/tools/ai-humanizer'
    | '/tools/caption-generator'
    | '/tools/chatbot-saas'
    | '/tools/domain-generator'
    | '/tools/portfolio-builder'
    | '/tools/proposal-generator'
    | '/tools/resume-builder'
    | '/tools/thumbnail-generator'
    | '/tools/website-generator'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-solutions'
    | '/blog'
    | '/contact'
    | '/portfolio'
    | '/pricing'
    | '/privacy-policy'
    | '/refund-policy'
    | '/services'
    | '/technologies'
    | '/terms-and-conditions'
    | '/tools'
    | '/tools/$toolId'
    | '/tools/ai-detector'
    | '/tools/ai-humanizer'
    | '/tools/caption-generator'
    | '/tools/chatbot-saas'
    | '/tools/domain-generator'
    | '/tools/portfolio-builder'
    | '/tools/proposal-generator'
    | '/tools/resume-builder'
    | '/tools/thumbnail-generator'
    | '/tools/website-generator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiSolutionsRoute: typeof AiSolutionsRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  PortfolioRoute: typeof PortfolioRoute
  PricingRoute: typeof PricingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ServicesRoute: typeof ServicesRoute
  TechnologiesRoute: typeof TechnologiesRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  ToolsRoute: typeof ToolsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technologies': {
      id: '/technologies'
      path: '/technologies'
      fullPath: '/technologies'
      preLoaderRoute: typeof TechnologiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-solutions': {
      id: '/ai-solutions'
      path: '/ai-solutions'
      fullPath: '/ai-solutions'
      preLoaderRoute: typeof AiSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/website-generator': {
      id: '/tools/website-generator'
      path: '/website-generator'
      fullPath: '/tools/website-generator'
      preLoaderRoute: typeof ToolsWebsiteGeneratorRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/thumbnail-generator': {
      id: '/tools/thumbnail-generator'
      path: '/thumbnail-generator'
      fullPath: '/tools/thumbnail-generator'
      preLoaderRoute: typeof ToolsThumbnailGeneratorRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/resume-builder': {
      id: '/tools/resume-builder'
      path: '/resume-builder'
      fullPath: '/tools/resume-builder'
      preLoaderRoute: typeof ToolsResumeBuilderRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/proposal-generator': {
      id: '/tools/proposal-generator'
      path: '/proposal-generator'
      fullPath: '/tools/proposal-generator'
      preLoaderRoute: typeof ToolsProposalGeneratorRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/portfolio-builder': {
      id: '/tools/portfolio-builder'
      path: '/portfolio-builder'
      fullPath: '/tools/portfolio-builder'
      preLoaderRoute: typeof ToolsPortfolioBuilderRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/domain-generator': {
      id: '/tools/domain-generator'
      path: '/domain-generator'
      fullPath: '/tools/domain-generator'
      preLoaderRoute: typeof ToolsDomainGeneratorRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/chatbot-saas': {
      id: '/tools/chatbot-saas'
      path: '/chatbot-saas'
      fullPath: '/tools/chatbot-saas'
      preLoaderRoute: typeof ToolsChatbotSaasRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/caption-generator': {
      id: '/tools/caption-generator'
      path: '/caption-generator'
      fullPath: '/tools/caption-generator'
      preLoaderRoute: typeof ToolsCaptionGeneratorRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/ai-humanizer': {
      id: '/tools/ai-humanizer'
      path: '/ai-humanizer'
      fullPath: '/tools/ai-humanizer'
      preLoaderRoute: typeof ToolsAiHumanizerRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/ai-detector': {
      id: '/tools/ai-detector'
      path: '/ai-detector'
      fullPath: '/tools/ai-detector'
      preLoaderRoute: typeof ToolsAiDetectorRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/$toolId': {
      id: '/tools/$toolId'
      path: '/$toolId'
      fullPath: '/tools/$toolId'
      preLoaderRoute: typeof ToolsToolIdRouteImport
      parentRoute: typeof ToolsRoute
    }
  }
}

interface ToolsRouteChildren {
  ToolsToolIdRoute: typeof ToolsToolIdRoute
  ToolsAiDetectorRoute: typeof ToolsAiDetectorRoute
  ToolsAiHumanizerRoute: typeof ToolsAiHumanizerRoute
  ToolsCaptionGeneratorRoute: typeof ToolsCaptionGeneratorRoute
  ToolsChatbotSaasRoute: typeof ToolsChatbotSaasRoute
  ToolsDomainGeneratorRoute: typeof ToolsDomainGeneratorRoute
  ToolsPortfolioBuilderRoute: typeof ToolsPortfolioBuilderRoute
  ToolsProposalGeneratorRoute: typeof ToolsProposalGeneratorRoute
  ToolsResumeBuilderRoute: typeof ToolsResumeBuilderRoute
  ToolsThumbnailGeneratorRoute: typeof ToolsThumbnailGeneratorRoute
  ToolsWebsiteGeneratorRoute: typeof ToolsWebsiteGeneratorRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsToolIdRoute: ToolsToolIdRoute,
  ToolsAiDetectorRoute: ToolsAiDetectorRoute,
  ToolsAiHumanizerRoute: ToolsAiHumanizerRoute,
  ToolsCaptionGeneratorRoute: ToolsCaptionGeneratorRoute,
  ToolsChatbotSaasRoute: ToolsChatbotSaasRoute,
  ToolsDomainGeneratorRoute: ToolsDomainGeneratorRoute,
  ToolsPortfolioBuilderRoute: ToolsPortfolioBuilderRoute,
  ToolsProposalGeneratorRoute: ToolsProposalGeneratorRoute,
  ToolsResumeBuilderRoute: ToolsResumeBuilderRoute,
  ToolsThumbnailGeneratorRoute: ToolsThumbnailGeneratorRoute,
  ToolsWebsiteGeneratorRoute: ToolsWebsiteGeneratorRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiSolutionsRoute: AiSolutionsRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  PortfolioRoute: PortfolioRoute,
  PricingRoute: PricingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ServicesRoute: ServicesRoute,
  TechnologiesRoute: TechnologiesRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  ToolsRoute: ToolsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
